version: "2"

services:
  gambit:
    build: ./gambit
    links:
      - mongo
    environment:
      - DB_URI=mongodb://mongo_1:27017
    volumes:
      - ./gambit/:/app

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"

  zookeeper:
    image: jplock/zookeeper:3.4.6
    ports:
      - "2182:2181"

  kafka:
    image: wurstmeister/kafka:latest
    hostname: kafka
    links:
      - zookeeper
    environment:
      KAFKA_ADVERTISED_HOST_NAME: "kafka"
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_CREATE_TOPICS: "Test:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    ports:
     - "9092:9092"
