version: "2"

services:
  gambit:
    build: ./gambit
    links:
      - mongo
    environment:
      - DB_URI=mongodb://mongo_1:27017/gambit
    volumes:
      - ./gambit/:/app

  rabbitmq:
    image: rabbitmq:latest
    ports:
      - "5672:5672"
    environment:
      RABBITMQ_DEFAULT_VHOST: 'dosomething'

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
